services:
  postgres:
    image: postgres:18
    container_name: tazama-postgres-1
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
      - ./backend/tcs-init.sql:/docker-entrypoint-initdb.d/tcs-init.sql:ro

  valkey:
    image: valkey/valkey:7.2.5
    container_name: tazama-valkey-1
    restart: unless-stopped
    ports:
      - 16379:6379
    volumes:
      - valkey_data:/data
  nats:
    image: nats:2
    container_name: tazama-nats-1
    restart: unless-stopped
    ports:
      - 14222:4222
      - 16222:6222
      - 18222:8222
    command: ["--jetstream", "--http_port", "8222"]
  sftp:
    image: atmoz/sftp
    container_name: tazama-sftp-1
    restart: unless-stopped
    ports:
      - 2222:22
    volumes:
      - sftp_data:/home/user/upload
    command: user:password:1001
    env_file:
      - ./backend/.env

  connection-studio-backend:
    container_name: connection-studio-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - sftp

volumes:
  postgres_data:
  valkey_data:
  sftp_data: